TARGET_FILE = "4.cpp"
OUTPUT_PREFIX = "barcode_"

ENABLE_IDENTIFIER_OBFUSCATION = True
ENABLE_CONSTANT_MUTATION = True
ENABLE_BOOLEAN_OBFUSCATION = True
ENABLE_DEAD_CODE_REMOVAL = True
ENABLE_INCLUDE_WRAPPING = True
ENABLE_WHITESPACE_DEGRADATION = True
ENABLE_RUNTIME_CONSTANT_OBFUSCATION = True
ENABLE_CONTROL_BODY_BRACING = True
ENABLE_CONTROL_FLOW_FLATTENING = True
ENABLE_CFG_POLLUTION = True
ENABLE_CONTAINER_ACCESSOR_REWRITES = True
ENABLE_STL_WRAPPER_REWRITES = True
ENABLE_OPAQUE_PREDICATE_INJECTION = True
ENABLE_DEAD_CODE_INJECTION = True
ENABLE_DEFINE_OBFUSCATION = True
ENABLE_COMMENT_STRIPPING = True
ENABLE_TMP_ADDITION_OBFUSCATION = True
ENABLE_FUNCTION_POINTER_INDIRECTION = True
ENABLE_FUNCTION_CLONING = True
ENABLE_DATA_FLOW_OBFUSCATION = True
ENABLE_MEMORY_ACCESS_OBFUSCATION = True
ENABLE_STATEMENT_REORDERING = True
ENABLE_LOOP_IDIOM_TRANSFORMATION = True
ENABLE_STYLOMETRIC_NOISE = True
TMP_MAX_RENDER_DEPTH = 12
ENABLE_STRING_LITERAL_ENCRYPTION = True
ENABLE_TYPE_LEVEL_OBFUSCATION = True
ENABLE_VIRTUAL_MACHINE_OBFUSCATION = True
ENABLE_VM_EXPRESSION_WRAPPERS = True

# Logging / diagnostics
VERBOSE_LOGGING = True
